### ISSUE TITLE
wish: option `minified=FALSE` to compile code not minified

### ISSUE THREAD

**Issue by TrantorM** [trafficonese/leaflet.extras#100]
Hi @bhaskarvk 
Is it possible to introduce an option `minified=FALSE`, which allows to compile the R code to html not minified?

**Comment by bhaskarvk** [comment]
I am not sure what exactly do you want ? Do you want the HTMLs/JS/CSS for the widget to be not minified ? For the HTMLs you'll have to raise the issue at the htmlwidgets repo.

**Comment by trafficonese** [comment]
I think he wants the JS/CSS sources not minified. 
This would make debugging much easier, especially if it would be possible to either include them in a minified (production) or unminified version (for debugging and learning purposes).

**Comment by trafficonese** [comment]
I am not sure what your usecase is for that.
For debugging I would suggest forking the repo and then setting `const mode = "development";` in the `webpack.config.js` before building it again. Then the JS-bindings will not get minified.

For production code I think it makes sense to leave everything minified..
