### ISSUE TITLE
[feature request] sidebar-v2 plugin

### ISSUE THREAD

**Issue by tim-salabim** [trafficonese/leaflet.extras#102]
Dear Bhaskar, 
as inquired on Twitter, I think it would be great to have the [sidebar-v2 plugin](https://github.com/Turbo87/sidebar-v2) accessible via leaflet.extras. It is particularly valuable to polish a "to-be-delivered" map with some explanatory text,  contact details, disclaimers etc. 
I have already posted a [SO question](https://stackoverflow.com/questions/46031077/r-leaflet-map-add-button-that-expands-on-hover-and-shows-some-text) of similar scope (which would also be sufficient for what I'd like to achieve) but having a fully fledged solution seems even better. 
Cheers

PS: no rush ;-)

**Comment by trafficonese** [comment]
The plugin is integrated in this repo
https://github.com/trafficonese/leaflet.extras2
