### ISSUE TITLE
[feature request] add clipped tile layer

### ISSUE THREAD

**Issue by tiernanmartin** [trafficonese/leaflet.extras#105]
I would like to add a tile layer for the focus area of a map I'm building, something like this:
![clipped-tiles-leaflet](https://user-images.githubusercontent.com/8197328/30517830-33c205e2-9b20-11e7-8b88-43f3b080ae77.PNG)

This image comes from @KoGor's [Dynamic Tile Clipping](http://bl.ocks.org/KoGor/c6838e2800c8dd8eaf96) example. The "dynamic" part of this example is really nice, but I would actually be fine with being able to provide a polygon that defines the bounds of the added tile layer - if that's easier to implement. 

Any chance of adding this feature?

**Comment by trafficonese** [comment]
I dont think there is an easy way to implement that, since it's not a plugin, but a mix of `leaflet.draw`, `d3` and `leaflet-0.7.3`
