### ISSUE TITLE
wish: Leaflet.wms plugin

### ISSUE THREAD

**Issue by ghost** [trafficonese/leaflet.extras#109]
It'd be amazing to get incorporate the leaflet.wms.js plugin into leaflet.extras at some point. A particularly useful part of this package would be to get support to identify features via GetFeatureInfo. I understand that this plugin officially only works with Leaflet.js 1.0, so granted this will have to wait for a while 
https://github.com/heigeo/leaflet.wms

**Comment by trafficonese** [comment]
The plugin is integrated in this repo
https://github.com/trafficonese/leaflet.extras2
