### ISSUE TITLE
[feature request] add leaflet-easyPrint plugin

### ISSUE THREAD

**Issue by rfineman** [trafficonese/leaflet.extras#114]
Would it be possible to add the easyPrint plugin (https://github.com/rowanwins/leaflet-easyPrint)?

![image](https://user-images.githubusercontent.com/33735858/32950234-9eebf4bc-cb73-11e7-9294-9e13ec1f86ee.png)

The other print map to image functions I've found keep things like the zoom control in the upper left corner and other inconveniences.

**Comment by rfineman** [comment]
Any luck with this? My ongoing research and trials and errors have been unfruitful. Thanks.

**Comment by bhaskarvk** [comment]
The earliest I can look into this is during X'mas holidays.

**Comment by nschwamm** [comment]
Was there any luck investigating this plugin?

**Comment by trafficonese** [comment]
The plugin is integrated in this repo
https://github.com/trafficonese/leaflet.extras2
