### ISSUE TITLE
[feature request] disable polygon dragging while editing

### ISSUE THREAD

**Issue by velaraptor** [trafficonese/leaflet.extras#115]
Is it possible to make polygons not completely move while editing? Can of like this example(http://leaflet.github.io/Leaflet.draw/docs/examples-0.7.x/full.html), where you edit, you cannot drag the polygon but edit the vertices. If anyone has any place to point to, I can write it up, just curious if someone can point me in the right direction. Thanks.

**Comment by bhaskarvk** [comment]
I guess I can make the drag handler optional.
