### ISSUE TITLE
registerPlugin then onRender not working for leaflet-velocity

### ISSUE THREAD

**Issue by bmkor** [trafficonese/leaflet.extras#125]
Not sure if I should ask here. If not, please kindly ignore it and I'll close this issue. Thanks. 

Followed examples on using plugin and onRender for leaflet plugin. It works but not for [leaflet-velocity](https://github.com/danwild/leaflet-velocity). Mind offering me help? Thanks a lot!

**Comment by trafficonese** [comment]
The [leaflet-velocity](https://github.com/danwild/leaflet-velocity) plugin is integrated in [leaflet.extras2](https://github.com/trafficonese/leaflet.extras2)
