### ISSUE TITLE
 Could not find function "addSearchMarker"

### ISSUE THREAD

**Issue by maaarangogo** [trafficonese/leaflet.extras#145]
Hi,

I recently changed my server provider. I have a shiny app and I'm using leaflet.extras. 
I installed the library (I've checked it twice) but in the new server appears: 

Error: could not find function "addSearchMarker"

I have exactly the same shiny files in both servers. Can't figure out what's going on.

You can see it here:

New: http://casadelasestrategias.com:3838/mapadevida/
Old: http://192.95.56.146:3838/mapadevida/

PD: I've also installed the library using install.packages and devtools::install_github functions
PD2: I've tried to add leaflet.extras:::addSearchMarker but it throws "object not found"

**Comment by trafficonese** [comment]
There is no function called `addSearchMarker`, were you looking for `addSearchFeatures`?
