### ISSUE TITLE
addSearchOSM control doesn't display

### ISSUE THREAD

**Issue by lweber2** [trafficonese/leaflet.extras#149]
addSearchOSM control doesn't show if not provided together with another search control, e.g. the following doesn't work:

```
leaflet() %>%
  addProviderTiles(providers$Esri.WorldStreetMap) %>%
  addSearchOSM()
```
However, if provided together with another search control, the search icon displays:
```
leaflet() %>%
  addProviderTiles(providers$Esri.WorldStreetMap) %>%
  addSearchOSM() %>%
  addSearchUSCensusBureau()
```

**Comment by trafficonese** [comment]
I cannot confirm. For me both examples work.
