### ISSUE TITLE
webGL Jsonlite Issue 

### ISSUE THREAD

**Issue by mdbeh** [trafficonese/leaflet.extras#151]
When I include a WebGLHeatmap on a leaflet map in Shiny, I'm getting the following warning:

> Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.

Looking around a bit, it seems like this is a standard message people are getting when they use vectors instead of lists in the manner described. It's not a fatal error, but it does clog up the console (it gets printed every time I change a map parameter), and I wouldn't want to deliver something that has a soon-to-be-obsolete control.

So any help/suggestions would be appreciated. BTW, I know there are other heatmap options, but I've found this webGL one to work best for me.

**Comment by bhaskarvk** [comment]
I'll be resuming development of leaflet.extras in Dec and will tackle this in that round. Thanks!

**Comment by trafficonese** [comment]
reprex:

library(shiny)  
library(leaflet)
library(leaflet.extras)

geoJson <- readr::read_file(
  "https://rawgit.com/benbalter/dc-maps/master/maps/historic-landmarks-points.geojson"
)

ui <- fluidPage(
  leafletOutput("map")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      setView(-77.0369, 38.9072, 12) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addWebGLGeoJSONHeatmap(
        geoJson, size = 30 , units = "px"
      ) %>%
      addGeoJSONv2(
        geoJson,
        markerType = "circleMarker",
        stroke = FALSE, fillColor = "black", fillOpacity = 0.7,
        markerOptions = markerOptions(radius = 2)
      )
  })
}
shinyApp(ui, server)
