### ISSUE TITLE
Leaflet search: Change search markers from circles to other visuals

### ISSUE THREAD

**Issue by kaimath** [trafficonese/leaflet.extras#171]
It would be great to be able to change the search marker, which is right now a circle marker, to say, a regular marker or even just a dot. If there's a way for me to do this manually, please let me know!

**Comment by trafficonese** [comment]
df79d4d should fix this. 
Also check out the example in [inst/examples/shiny/search/features_app.R](https://github.com/trafficonese/leaflet.extras/commit/df79d4dfdce55801da4092bea245386f23633ad6#diff-4c346876d4144e7dafafba0e2d85d40d0c5f91b73a7944396f3e93b5169b7523)
