### ISSUE TITLE
any chance we can insert arbitrary javascript on popups?

### ISSUE THREAD

**Issue by dan-reznik** [trafficonese/leaflet.extras#176]
would love to include a plotly.js within a popup...

**Comment by timelyportfolio** [comment]
@dan-reznik This [example](https://gist.github.com/timelyportfolio/098a1bf77caf2fd0267e3116f128ad13) should work again now.  I had to modify last week for plotly dependencies.  Also if static is ok you might like @tim-salabim [`leafpop`](https://github.com/r-spatial/leafpop).
