### ISSUE TITLE
Adding Drivability

### ISSUE THREAD

**Issue by Stephonomon** [trafficonese/leaflet.extras#178]
Adding the ability to have a layer that gives uses drive times can help with maps where we need to determine the driving time a patient would take to come to various hospital settings. There already is a leaflet js library for it.
https://github.com/traffordDataLab/leaflet.reachability

**Comment by trafficonese** [comment]
The plugin is integrated in 
[leaflet.extras2](https://github.com/trafficonese/leaflet.extras2)
