### ISSUE TITLE
favorDoubleClick

### ISSUE THREAD

**Issue by seabass20** [trafficonese/leaflet.extras#190]
Hi! I haven't been able to integrate the favorDoubleClick plug-in into my leaflet map in RShiny. Would love for it to be included in the extras package!

**Comment by trafficonese** [comment]
The only place where I can find the JS-src is in the source-code of https://azavea.github.io/Leaflet.favorDoubleClick/
Is this still an active plugin on github or npm?

**Comment by trafficonese** [comment]
The example is not working and no github repo. I'll close this
