### ISSUE TITLE
Leaflet.StyledLayerControl & Leaflet.GroupedLayerControl Plugins 

### ISSUE THREAD

**Issue by hugovr24** [trafficonese/leaflet.extras#202]
Hello,

Would you add the Leaflet.StyledLayerControl(https://github.com/davicustodio/Leaflet.StyledLayerControl) & Leaflet.GroupedLayerControl (https://github.com/ismyrnow/leaflet-groupedlayercontrol) Plugins to the leaflet.extras? I think having the option to customizes groups and overlay groups in leaflet maps would a great addition to the package as it gives us more freedom to organize our data displayed

Thank you,
Hugo

**Comment by rafabelokurows** [comment]
First, thanks for the amazing package. 

I agree with the request, although it's more of an aesthetic concern, it would be a very nice addition to the leaflet R toolbox.

Thank you!

**Comment by trafficonese** [comment]
I totally agree that it would be nice to have, but there are some problems IIRC..

The `Leaflet.StyledLayerControl` plugin doesnt work with leaflet > 1 and the last activity was 4 years ago.. So I doubt there would be any update anytime soon.

and `leaflet-groupedlayercontrol` is 6 years old and not actively maintained.

I can still try them out and see if they work with the R leaflet version.

**Comment by rafabelokurows** [comment]
Thanks for the quick reply!

If you could be so kind as to check another alternative:
https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree

![image](https://github.com/trafficonese/leaflet.extras/assets/55976107/45f312d0-96ea-4c01-98d9-471e432a472a)

While it doesn't do the same as the other ones, it would allow the user to group and organize overlaygroups.
If I'm seeing this correctly, it works with Leaflet > 1
