### ISSUE TITLE
add functionality to addWMSLegend() to set a legend-title

### ISSUE THREAD

**Issue by jlhelling** [trafficonese/leaflet.extras#219]
It would be great to have an option to include a title for legends created via the addWMSLegend()-function :) Especially when having a map with several layers this could help to give the map's user a better overview.

**Comment by trafficonese** [comment]
With commit [3f27bff](https://github.com/trafficonese/leaflet.extras/commit/3f27bff1fbd417d712d5355b6b7e6df55e9b2cad) you can now pass `title`, `titleStyle `and `titleClass`
