### ISSUE TITLE
addSearchOSM() not working in exported Standalone Web Pages

### ISSUE THREAD

**Issue by PureLemon** [trafficonese/leaflet.extras#225]
OpenStreetMap has updated their Authentication and I believe it's breaking addSearchOSM().

The addSearchOSM() search feature will not work with a Leaflet map that has been Exported to a Standalone Web Page. Here is the link to a [July 2024 OSM Wiki Update](https://wiki.openstreetmap.org/wiki/2024_authentication_update) that might have something to do with this suddenly not working.

Below, I've added an image of the Access Blocked page that appears in the browser console when attempting to use the OSM search. Here is the [Usage Policy Link](https://operations.osmfoundation.org/policies/nominatim/) that is linked in the image.

![image](https://github.com/user-attachments/assets/4481fcb3-6e96-437e-b65d-be5f9033c379)

When using RStudio's integrated Viewer the OSM search works without any issues. The issue only comes up when exporting the Leaflet to a Web Page and attempting to use the search there.

The following code is the minimum required to replicate the issue.
```r
library(leaflet)
library(leaflet.extras)
leaflet()  %>% 
  addTiles() %>% 
  addSearchOSM()
```

**Comment by trafficonese** [comment]
I cannot reproduce this.
The OSM search is working for me in an exported leaflet map, in a shiny app and in the RStudio Viewer.
Maybe you made too many requests?

> No heavy uses (an absolute maximum of 1 request per second).

**Comment by PureLemon** [comment]
Sorry about that, after some testing this seems to be an issue only effecting devices at my work. My personal computer had no problem with the OSM Search while my work laptop still couldn't get it to work. This must be a security problem with our work devices. I apologize for making this Issue post!

**Comment by trafficonese** [comment]
No worries, I'll close the issue then :)
