### ISSUE TITLE
GIBS

### ISSUE THREAD

**Issue by bhaskarvk** [trafficonese/leaflet.extras#29]
https://github.com/aparshin/leaflet-GIBS

**Comment by bhaskarvk** [comment]
It probably makes sense to have a dedicated package for GIBS given the plethora of features it supports

**Comment by mdsumner** [comment]
We discussed this today, we have staff using gdal_translate to download georeferenced imagery from this and draw information over the maps of sea ice. It's a clear use-case with mapedit if we can get this into R's leaflet support for the polar projection. I'll pursue with our data centre programmers but any leads or explorations you have would be helpful.

**Comment by trafficonese** [comment]
The plugin is integrated in this repo
https://github.com/trafficonese/leaflet.extras2
