### ISSUE TITLE
Polarmaps.js

### ISSUE THREAD

**Issue by bhaskarvk** [trafficonese/leaflet.extras#30]
https://github.com/GeoSensorWebLab/polarmap.js

**Comment by bhaskarvk** [comment]
It makes sense to have a dedicated package for this, as Polarmaps.js requires a custom Map object.

**Comment by trafficonese** [comment]
Not working for leaflet v1 and no updates in 6 years..
https://github.com/GeoSensorWebLab/polarmap.js/issues/6
