### ISSUE TITLE
CartoDB

### ISSUE THREAD

**Issue by bhaskarvk** [trafficonese/leaflet.extras#31]
https://carto.com/docs/carto-engine/carto-js/

**Comment by bhaskarvk** [comment]
CartoDB is huge and makes sense to track it in a dedicated package.

**Comment by trafficonese** [comment]
https://carto.com/developers/carto-js/v3/

`This library is still under support but it will not be further developed. We don’t recommend starting new projects with it as it will eventually become deprecated.`
