### ISSUE TITLE
Temporal Viz support

### ISSUE THREAD

**Issue by bhaskarvk** [trafficonese/leaflet.extras#34]
Currently these are the options to visualize spatiotemporal data.

- [TimeDimension](https://github.com/socib/Leaflet.TimeDimension) 
    - Perhaps the most feature complete plugin. 
    - Supports WMS and GeoJSON data with time element. 
    - For the WMS part requires a proxy on the server to avoid CORS issues.
    - Could be an overkill for our visualization needs.
- [TimeSlider](https://github.com/dwilhelm89/LeafletSlider)
    - Simple and straight forward enough.
    - Supports only markers.
- [Playback](https://github.com/hallahan/LeafletPlayback)
    -  Supports plotting GPX point data.
- [Timeline](https://github.com/skeate/Leaflet.timeline)
    - This is by far the most easiest and fairly feature rich
    - Takes GeoJSONs with time dimensions as properties
- [Realtime](https://github.com/perliedman/leaflet-realtime)
    - Polls a GeoJSON/p source
    - Serves an entirely different purpose than the rest of the alternatives, so might be worthwhile to add it regardless.

My vote goes to Timeline as it's very easy to implement. But I am willing to listen to arguments for others, especially TImeDimension.

cc @tim-salabim @jcheng5 @mdsumner

**Comment by tim-salabim** [comment]
from my point of view I am happy with whatever plugin is able to work with native R spatial objects, i.e. sp, sf, raster. Though from what I gather, these plugins really only work with GeoJSON and WMS served rasters correct? If that is the case, then I am not too fussed as we can transform to GeoJSON before rendering even if that adds another layer of overhead. Regarding rasters, we need to come up with a good solution for local rasters as this is what most people work with in my opinion. However, I'd be interested to hear other peoples opinions as I am not working at all with proper space-time data. @edzer would be nice to hear your thoughts on this.

**Comment by johnpauls** [comment]
Being able to work with local rasters would be very nice - there is lots of climate and land use data I would like to display in this manner.

**Comment by WillCHL** [comment]
Support for files like GeoJSON or R spatial object would also be my priority over WMS-T.  I saw the 'R + leaflet + Time Dimension Plugin' youtube video which looks really nice.  Anyway an up vote for this implementation, I'm hoping to use it in a Shiny App.

**Comment by trafficonese** [comment]
There are a number of time-related plugins available for R:

[leaftime](https://cran.r-project.org/web/packages/leaftime/index.html) offers [Timeline](https://github.com/skeate/Leaflet.timeline)

[leaflet.extras2](https://cran.r-project.org/web/packages/leaflet.extras2/index.html) offers [Playback](https://github.com/hallahan/LeafletPlayback), [MovingMarker](https://github.com/ewoken/Leaflet.MovingMarker), [LeafletSlider](https://github.com/dwilhelm89/LeafletSlider)

[TimeseriesMap](https://mazamascience.github.io/tiotemp/articles/articles/Oregon_LaborDayFires.html) - Creates a timeseries leaflet map that displays point location time series data and allows playback with a slider and "Play" button.


I will have a closer look at `TimeDimension` and consider whether I can/should integrate it.

Feel free to reopen the issue if you're missing some functionality.
