### ISSUE TITLE
support for animated markers

### ISSUE THREAD

**Issue by cole-brokamp** [trafficonese/leaflet.extras#39]
Some possible plugins to integrate are:

https://github.com/openplans/Leaflet.AnimatedMarker
https://github.com/ewoken/Leaflet.MovingMarker

**Comment by bhaskarvk** [comment]
Thanks I'll add these to my backlog.

**Comment by byzheng** [comment]
+1 for moving marker. It is useful to show my running logs.

**Comment by bhaskarvk** [comment]
Is this a better alternative to both those plugins https://github.com/hallahan/LeafletPlayback ?

**Comment by byzheng** [comment]
Yes this plugin is more interesting.

**Comment by cole-brokamp** [comment]
Yes, that looks better.  One feature I was hoping for was the ability to plot the trailing line after the marker is animated across it.  Something like this example usage:

http://zevross.com/blog/2014/12/09/use-d3-to-gradually-reveal-points-on-a-leaflet-web-map/

**Comment by bhaskarvk** [comment]
What concerns me about the AnimatedMarker and MovingMarker plugin is that the speed is set rather arbitrarily while the LeafletPlayback deduces the speed from the timestamped entries.

**Comment by dwy904** [comment]
https://github.com/rubenspgcavalcante/leaflet-ant-path

This is cool if it could be used for airline routes visualization. I am very looking for this feature.

**Comment by theshauryasingh** [comment]
https://github.com/openplans/Leaflet.AnimatedMarker
https://github.com/ewoken/Leaflet.MovingMarker
https://github.com/hallahan/LeafletPlayback 

but how to use these plugins in R, I am not able to figure out. please help

**Comment by harryprince** [comment]
+1 animatedMarker to display trajectory.

**Comment by trafficonese** [comment]
The following plugins are integrated in [leaflet.extras2](https://github.com/trafficonese/leaflet.extras2)

[Ant Path](https://github.com/rubenspgcavalcante/leaflet-ant-path)
[Moving Markers](https://github.com/ewoken/Leaflet.MovingMarker)
[Playback](https://github.com/hallahan/LeafletPlayback)
