### ISSUE TITLE
Wish: mesh tools

### ISSUE THREAD

**Issue by mdsumner** [trafficonese/leaflet.extras#54]
There are a number of interesting mesh packages by this user:

https://github.com/mikolalysenko/simplicial-complex

The simplicial complex is the one I want, though may need to explore how it relates to others at this account that are more up to date.

**Comment by trafficonese** [comment]
Although this looks very interesting, I think it doesn't fit the purpose of `leaflet.extras`. 
Since it's not a Leaflet plugin, maybe it's better suited for a separate package that bundles these functionalities together.
If I misunderstood or misinterpreted it, feel free to reopen this issue.
