### ISSUE TITLE
Add hexbin?

### ISSUE THREAD

**Issue by happyshows** [trafficonese/leaflet.extras#63]
Hi,

Just curious, is it possible to add hex bin capability to this package?

thanks.

**Comment by bhaskarvk** [comment]
Sure, do you know of a leaflet plugin that provides hex binning capabilities ?

**Comment by happyshows** [comment]
I'm not sure if there's native plugin available. I was searching for this capability today since ggmap can do it (without the interactive capability that leaflet provides)

**Comment by bhaskarvk** [comment]
Do you have example code from ggmap I can look at ?

**Comment by happyshows** [comment]
It's been a while and I couldn't find the link, here is something similiar:
http://unconj.ca/blog/custom-hexbin-functions-with-ggplot.html

**Comment by bhaskarvk** [comment]
OK I found something https://jsfiddle.net/s8f4ks9m/1/. I will what I can do to support this.

**Comment by ccamara** [comment]
I would also love to see that feature implemented.

I've seen these resources that achieve that in leaflet + D3:

* http://bl.ocks.org/tnightingale/4668062
* https://github.com/Asymmetrik/leaflet-d3

**Comment by trafficonese** [comment]
The [d3-hexbin plugin](https://github.com/bluehalo/leaflet-d3#hexbins-api) is integrated in this repo
https://github.com/trafficonese/leaflet.extras2
