### ISSUE TITLE
Support for leaflet-mapkey-icon

### ISSUE THREAD

**Issue by metanoid** [trafficonese/leaflet.extras#88]
http://mapkeyicons.com/ looks to be a font for maps.
They have a leaflet plugin here:
https://github.com/mapshakers/leaflet-mapkey-icon
If possible, I thnik adding this plugin to leaflet.extras would be a good idea.

**Comment by bhaskarvk** [comment]
I will be happy to add, but adding icon support is really easy. If you want to take a crack at it, I will be ore than happy to review a PR. Check the other icon lib code for reference.

**Comment by trafficonese** [comment]
The plugin is integrated in this repo
https://github.com/trafficonese/leaflet.extras2
