### ISSUE TITLE
has timeline (or an alternative) been implemented?

### ISSUE THREAD

**Issue by SimonCoulombe** [trafficonese/leaflet.extras#90]
Hi!
Thanks for this package.

A few months ago it was posted that leaflet.timeline would soon be added.   Is this still in the works?
thanks
https://github.com/rstudio/leaflet/issues/158

**Comment by bhaskarvk** [comment]
After UseR! I promise.

**Comment by SimonCoulombe** [comment]
thanks for replying - can't wait to try it out!

**Comment by bhaskarvk** [comment]
I am working on time dimension. I am about 2 weeks away from making an initial public release.

**Comment by SimonCoulombe** [comment]
thanks for the update!

**Comment by heliostat** [comment]
Thanks, just started using this package --- loving it --- and looking forward to having timeline integrated...

**Comment by jahor104** [comment]
Hope the release is going to come soon! :)

**Comment by bhaskarvk** [comment]
I am deep in day job to work on this currently. I have an incomplete branch but need solid 2 weeks of spare time to finish it and unfortunately I don't have that time at the moment.

**Comment by pythianconsultants** [comment]
@bhaskarvk waiting very eagerly for Timeline or Playback! Will be of immense use. Keep up the great work you are doing!

**Comment by sobradob** [comment]
@bhaskarvk  I too am very thankful for your work so far. Just commenting here to make sure I get an update when the update goes up!

**Comment by linkgan** [comment]
+1 can't wait for the timeline implementation. it would help tremendously with my project if this was available. cheers!

**Comment by yingtaoxie** [comment]
Having gone through all the previous issues and glad to know that the task is still being developed! Really eager to see the output and use it in a project.

**Comment by sobradob** [comment]
Hi all,

Two "similar" solutions I built (with code): 
- [no leaflet, using gganimate](http://boazsobrado.com/blog/2019/01/13/where-i-was-in-2018/)
- [using leaflet](http://boazsobrado.com/blog/2018/02/08/leaflet-timeline-in-r/)

**Comment by trafficonese** [comment]
I will close this, as there are several time-related plugins available now:

[leaftime](https://github.com/timelyportfolio/leaftime)

and in [leaflet.extras2](https://github.com/trafficonese/leaflet.extras2) the following plugins are interated:
[Moving Markers](https://github.com/ewoken/Leaflet.MovingMarker)
[Playback](https://github.com/hallahan/LeafletPlayback)
[Timeslider](https://github.com/dwilhelm89/LeafletSlider)


Feel free to reopen when you find another useful time-plugin.
